jarvis-slackbot:
  image: fvierbergen/jarvis-slackbone
  mem_limit: "1000000000"
  ports:
    - "80:80"
  environment:
    - "SONAR_API_HOST=https://nemo.sonarqube.org"
    - "SONAR_API_RESOURCE_KEY=org.codehaus.sonar-plugins:ebcdic-ascii-converter"
    - "SLACK_API_TOKEN=palceholder-replace-me"